import type { Metadata } from "next";
import { Inter, Rajdhani } from 'next/font/google'
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const inter = Inter({
  weight: ['300', '400', '500', '600'],
  subsets: ["latin"],
  variable: '--font-inter',  // ← faltava isso
});

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-rajdhani',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={`${inter.variable} ${rajdhani.variable} text-zinc-600`}>
      {/* ↑ aplicar as variáveis aqui é o que faltava */}
      <body className={`${inter.className} text-zinc-600`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="background-main w-full">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  )
}